language: python
python:
  - "2.6"
  - "2.7"
# test against different versions of Django
env:
  - DJANGO_VERSION=">=1.3,<1.4"
  - DJANGO_VERSION=">=1.4,<1.5"
  allow_failures:
    - DJANGO_VERSION=">=1.5,<1.6"
# command to install dependencies
install:
  - "pip install --use-mirrors ."
  - "pip install --use-mirrors django-app-tester Django$DJANGO_VERSION"
# command to run tests
script: django_apptest issues
